FROM registry.redhat.io/ubi9/nodejs-22:9.6-1755075210 AS node-builder
USER root
WORKDIR /app
COPY ui ui
COPY Makefile Makefile
RUN make build-ui

FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.25 as go-builder
USER root
WORKDIR /go/src/github.com/perses/perses
COPY . .
COPY --from=node-builder /app/ui/app/dist ui/app/dist
RUN mkdir /perses
RUN mkdir /plugins
ENV GOFLAGS="-mod=readonly"
RUN make build-api
RUN make build-cli

FROM gcr.io/distroless/static-debian12:nonroot

LABEL maintainer="The Perses Authors <perses-team@googlegroups.com>"

COPY --from=go-builder                          /go/src/github.com/perses/perses/bin/perses        /bin/perses
COPY --from=go-builder                          /go/src/github.com/perses/perses/bin/percli        /bin/percli
COPY                                            LICENSE            /LICENSE
COPY --from=go-builder --chown=nonroot:nonroot  /go/src/github.com/perses/perses/plugins-archive/   /etc/perses/plugins-archive/
COPY                                            docs/examples/config.docker.yaml     /etc/perses/config.yaml
COPY --from=go-builder --chown=nonroot:nonroot  /perses            /perses
COPY --from=go-builder --chown=nonroot:nonroot  /plugins           /etc/perses/plugins

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
