security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - "*"
      - actions:
          - create
        scopes:
          - Project
    kubernetes: true
  authentication:
    disable_sign_up: true
    providers:
      enable_native: false
      kubernetes:
        enabled: true
        kubeconfig: /home/pyurkovi/.kube/config

database:
  file:
    folder: "/home/pyurkovi/projects/forks/perses/dev/local_db"
    extension: "json"
    case_sensitive: false

provisioning:
  folders:
    - "/home/pyurkovi/projects/forks/perses/dev/data"

ephemeral_dashboard:
  enable: true
  cleanup_interval: 1h

frontend:
  explorer:
    enable: true

  important_dashboards:
    - project: "perses"
      dashboard: "Demo"
    - project: "perses"
      dashboard: "NodeExporter"
    - project: "perses"
      dashboard: "Benchmark"
    - project: "testing"
      dashboard: "Defaults"
    - project: "testing"
      dashboard: "StatChartPanel"
    - project: "testing"
      dashboard: "MarkdownPanel"

  information: |-
    # Hello World
    ## File Database setup

plugin:
  enable_dev: true
  archive_path: "/home/pyurkovi/projects/forks/perses/plugins-archive"
