// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/peteryurkovich/perses/pkg/model/api/v1

package v1

import "github.com/peteryurkovich/perses/cue/model/api/v1/common"

#ProjectSpec: {
	display?: null | common.#Display @go(Display,*common.Display)
}

#Project: _
